version: 2.1

configuration:
  - ubuntu_version: &ubuntu_version ubuntu-2004:current

parameters:
  docker-image-casper-cpp-sdk:
    default: "polishcode/matterfi-casper-cpp-sdk-ubuntu:1"
    type: string

executors:
  executor_ubuntu_large:
    machine:
      image: *ubuntu_version
    resource_class: xlarge
      
commands:
  cmd_prepare_env:
    description: "command to prepare all build dependencies: code, vcpkg, tools"
    parameters:
      docker-image:
        type: string
    steps:
      - run:
          name: "pull docker image"
          command: docker pull <<parameters.docker-image>>
      - checkout
            
jobs:
  build-linux:
    parameters:
      docker-image:
        type: string
    executor: executor_ubuntu_large
    steps:
      - cmd_prepare_env:
          docker-image: <<parameters.docker-image>>

workflows:
  casper-cpp-sdk-linux:
    when: true
    jobs:
      - build-linux:
          name: build & test on linux
          docker-image: <<pipeline.parameters.docker-image-casper-cpp-sdk>>